spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dataset
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true

app:
  api-key: c92dcd54-eca5-4e21-974d-6379996bd3e5
  nayn-co: /newstitle/naynco
  evrensel: /newstitle/evrensel
  dokuz-sekiz: /newstitle/dokuzsekiz
  txt-path: /home/suleymancan/haber/dataset



